#!/bin/sh -f

. ./find_bush

. ${bush_home}/args
. ${bush_home}/g4args

save_dir=`pwd`

#/////////////////////////////////////////////////////////////
#/// cleanup comres //////////////////////////////////////////
#/////////////////////////////////////////////////////////////
${bush_home}/find_rm ../comres '*.*'
#/////////////////////////////////////////////////////////////
#/// get some files from ioda and put them in comres /////////
#/////////////////////////////////////////////////////////////

cd ..
from=../../softinex/ioda/res

if [ ! -d ${from} ] ; then
  echo "directory ${from} not found"
  exit
fi

files=""
files="${files} arialbd.ttf helveticabd.ttf courbd.ttf lucidagrandebd.ttf" #gui fonts.
files="${files} helvetica.ttf"
#files="${files} stixgeneral.otf"

# cam panel :
files="${files} move2red.jpg crazyeye_run.jpg flip_flop.jpg"
files="${files} close.jpg edit.jpg edit_undo.jpg"
files="${files} object_rotate_left.jpg stop_object_rotate_left.jpg"

# main gui :
files="${files} go_home_large.jpg turn_around.jpg"
files="${files} movie_camera.jpg system_config_boot.jpg"

# rwc items :
files="${files} sidebar_photos.jpg stop_diaporama.jpg"
files="${files} cursor.jpg"

# main menu :
files="${files} application_exit.jpg"
files="${files} edit_clear.jpg"
files="${files} document_export.jpg"
files="${files} routing_step.jpg console.jpg tools.jpg"
files="${files} connect_to_wall.jpg"

files="${files} ioda_cube.jpg"
files="${files} set_current_region.jpg edit_plot.jpg"
files="${files} histo.jpg"
files="${files} files.jpg"

for file in ${files} ; do
  /bin/cp ${from}/${file} ./comres/.
done

/bin/cp ${from}/ioda.style ./comres/MEMPHYS_vis.style

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/// copy app specific res files into comres /////////////////
#/////////////////////////////////////////////////////////////
files=""
files="${files} clear_event.jpg clear_histo.jpg event.jpg"
files="${files} icon.jpg icon.png"
files="${files} stixgeneral.otf"
files="${files} stop_events.jpg vis_events.jpg white.jpg"

# for sim :
files="${files} init.g4m job_options.mac input.memphys budimir.memphys"

files="${files} pythia_8170_xmldoc.zip"

if [ ${build_geant4_10x} = "yes" ] ; then
  files="${files} g4emlow_6_50.zip g4ensdfstate_2_1.zip g4ndl_4_5.zip"
  files="${files} g4saiddata_1_1.zip photonevaporation_4_3_2.zip"
  files="${files} g4ndl_4_5_reduced.zip" # for Android.
  files="${files} photonevaporation_4_3_2_reduced.zip" # for Android.
else # g4.9.5 :
  files="${files} g4emlow_6_50.zip g4ndl_3_12.zip"
  files="${files} photonevaporation_4_3_2.zip"
fi

for file in ${files} ; do
  /bin/cp ../res/${file} ../comres/.
done

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
. ${bush_home}/and_app_res
. ${bush_home}/ios_app_res

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
if [ ${build_geant4_10x} = "yes" ] ; then
  /bin/mv ../Android/res/raw/g4ndl_4_5_reduced_zip.jet ../Android/res/raw/g4ndl_4_5_zip.jet 
  /bin/mv ../Android/res/raw/photonevaporation_4_3_2_reduced_zip.zip ../Android/res/raw/photonevaporation_4_3_2_zip.zip 
  /bin/rm -f ../Android/res/raw/photonevaporation_4_3_2_zip.jet
  /bin/rm -f ../comres/g4ndl_4_5_reduced.zip
  /bin/rm -f ../comres/photonevaporation_4_3_2_reduced.zip
fi

