#!/bin/sh -f

. ./find_bush

. ${bush_home}/args
. ${bush_home}/g4args

save_dir=`pwd`

${bush_home}/find_rm ../comres '*.*'

#/////////////////////////////////////////////////////////////
#/// from ioda: //////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
. ../../ioda/mgr/cp_std

files="${files} ioda_cube.jpg"
files="${files} histo.jpg"
files="${files} package_edutainment.jpg"
files="${files} gun.jpg"
files="${files} edit_geom.jpg"
files="${files} clear_histo.jpg"

for file in ${files} ; do
  /bin/cp ../../ioda/res/${file} ../comres/.
done

/bin/cp ../../ioda/res/ioda.style ../comres/MEMPHYS_vis.style

#/////////////////////////////////////////////////////////////
#/// from inlib : ////////////////////////////////////////////
#/////////////////////////////////////////////////////////////

. ../../inexlib/inlib/mgr/cp_insh

for file in ${files} ; do
  /bin/cp ../../inexlib/inlib/inlib/insh/scripts/${file} ../comres/.
done

#/////////////////////////////////////////////////////////////
#/// from exlib : ////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
. ../../inexlib/exlib/mgr/cp_insh

for file in ${files} ; do
  /bin/cp ../../inexlib/exlib/exlib/insh/scripts/${file} ../comres/.
done

#/////////////////////////////////////////////////////////////
#/// copy app specific res files into comres /////////////////
#/////////////////////////////////////////////////////////////
files=""
files="${files} icon.jpg icon.png"
files="${files} startup.insh"
files="${files} about.insh"
files="${files} event.insh"
files="${files} add_axes.insh"
files="${files} camera_default.insh"
files="${files} camera_top.insh"
files="${files} gui_main.insh"
files="${files} icon.insh"

# for sim :
files="${files} init.g4m job_options.mac input.memphys budimir.memphys"

files="${files} pythia_8170_xmldoc.zip"

if [ ${build_geant4_10x} = "yes" ] ; then
  files="${files} g4emlow_6_50.zip g4ensdfstate_2_1.zip g4ndl_4_5.zip"
  files="${files} g4saiddata_1_1.zip photonevaporation_4_3_2.zip"
  files="${files} g4ndl_4_5_reduced.zip" # for Android.
  files="${files} photonevaporation_4_3_2_reduced.zip" # for Android.
else # g4.9.5 :
  files="${files} g4emlow_6_50.zip g4ndl_3_12.zip"
  files="${files} photonevaporation_4_3_2.zip"
fi

for file in ${files} ; do
  /bin/cp ../res/${file} ../comres/.
done

cd ${save_dir}

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
. ${bush_home}/and_app_res
. ${bush_home}/ios_app_res

#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
#/////////////////////////////////////////////////////////////
if [ ${build_geant4_10x} = "yes" ] ; then
  /bin/mv ../Android/res/raw/g4ndl_4_5_reduced_zip.jet ../Android/res/raw/g4ndl_4_5_zip.jet 
  /bin/mv ../Android/res/raw/photonevaporation_4_3_2_reduced_zip.zip ../Android/res/raw/photonevaporation_4_3_2_zip.zip 
  /bin/rm -f ../Android/res/raw/photonevaporation_4_3_2_zip.jet
  /bin/rm -f ../comres/g4ndl_4_5_reduced.zip
  /bin/rm -f ../comres/photonevaporation_4_3_2_reduced.zip
fi

