#!/bin/sh -f

if [ "`uname -n | grep iridium`" != "" ] ; then
  g4data_home=/nfs/users/gbarrand/usr/local/geant4/data_103
else
  g4data_home=/usr/local/geant4/data_103
fi

if [ ! -d ${g4data_home} ] ; then
  echo "unfold_g410x : directory ${g4data_home} not found."
  exit    
fi    

save_dir=`pwd`

cd ${g4data_home}
unzip -q ${save_dir}/../comres/g4ndl_4_5.zip
unzip -q ${save_dir}/../comres/g4emlow_6_50.zip
unzip -q ${save_dir}/../comres/g4ensdfstate_2_1.zip
unzip -q ${save_dir}/../comres/g4saiddata_1_1.zip
unzip -q ${save_dir}/../comres/photonevaporation_4_3_2.zip
cd ${save_dir}
